version: '3'
services:
  wordpress_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: wordpress_db
    restart: unless-stopped
    volumes:
      - ./wordpress_db:/config
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}  
    networks:
      - internal

  wordpress:
    image: wordpress:latest
    container_name: wordpress_website
    restart: unless-stopped
    volumes:
      - ./wordpress_prod:/var/www/html   
    environment:
      - WORDPRESS_DB_HOST=wordpress_db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`yourdomain.com`)
      - traefik.http.routers.wordpress.entrypoints=websecure
      - traefik.http.services.wordpress.loadbalancer.server.port=80	  
    networks:
      - internal
      - web
    depends_on:
      - wordpress_db

  phpmyadmin:
    image: phpmyadmin
    container_name: wordpress_pma
    restart: unless-stopped
    environment:
      - PMA_HOST=wordpress_db:3306
      - UPLOAD_LIMIT=512M
    labels:
      - traefik.enable=true
      - traefik.http.routers.pma.rule=Host(`pma.yourdomain.com`)
      - traefik.http.routers.pma.entrypoints=websecure
      - traefik.http.services.pma.loadbalancer.server.port=80
    networks:
      - internal
      - web
    depends_on:
      - wordpress_db

volumes:
  wordpress_db:
  wordpress_prod:
networks:
  web:
    external: true
  internal:
    external: false
